name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ↓ ADD THIS PERMISSIONS BLOCK
permissions:
  contents: read
  pages: write
  id-token: write  # ← CRUCIAL FOR DEPLOYMENT

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
